### ISSUE TITLE
Results are not properly calculated

### ISSUE THREAD

**Issue by Planeshifter** [Planeshifter/qality.js#35]
Right now, every answer for multiple-choice questions is counted as correct. In contrast, for the input fields everything works as expected.

**Comment by Phalanstere** [comment]
Sounds strange. I will have a look.

**Comment by Phalanstere** [comment]
I've checked it meanwhile. - Maybe the problem was of a psychological nature. - In the default values, every answer had 1 point, whether it was right or wrong. Now I changed that. A random procedure decides whether answer1 or 2 is right and assigns the appropriate points: 1 if it is right,  zero if wrong.
You can check it if you load the **test01.json** file in the test folder.
Clicking **right** should yield a point, wrong none. 
We could write a test for that.
